
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file: .env

  app:
    build: .
    restart: always # comment out this line prior to one off run commands
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./prototype:/prototype
      - ./data:/data
